name: AI Image Generator CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Build and test with CMake
      run: |
        mkdir -p build
        cd build
        cmake -DWITH_HF_TOKEN=OFF ..
        cmake --build . --target run_tests

    - name: Run specific tests
      run: |
        cd build
        source .venv/bin/activate
        python -m pytest ../tests/ -v
